name: build-resume


on:
  push:
    tags:
      - '*'

jobs:
  resume:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate the resume
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            dist/cv-en.min.pdf
